#!/bin/bash

#### taken from https://stackoverflow.com/a/39454426 and modified

if [ $# -lt 1 ]
then
cat << HELP

dockertags  --  list all tags for a Docker image on a remote registry.

EXAMPLE:
    - list all tags for ubuntu:
       dockertags ubuntu

    - list all php tags containing apache:
       dockertags php apache

HELP
fi

image="$1"
docker_username="$2"
docker_password="$3"

if [ -z "$docker_username" ] || [ -z "$docker_password" ]; then
  tags=$(curl -s https://registry.hub.docker.com/v1/repositories/${image}/tags | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}')
else
  token=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'$docker_username'", "password": "'$docker_password'"}' https://hub.docker.com/v2/users/login/ | sed -e 's/{"token": "//g' -e 's/"}//g')
  tags=$(curl -s -H "Authorization: JWT ${token}" https://registry.hub.docker.com/v1/repositories/${image}/tags | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}')
fi


echo "${tags}"
