#!/bin/bash

set -o nounset
set -o errexit
#set -o xtrace

if ! command -v gpg &> /dev/null; then
  echo "gpg is not installed"
  exit 1
fi

function usage() {
  echo "usage: $(basename $0) <filename>"
}

if [[ $# -ne 1 ]]; then
  usage
  exit 1
fi

filename="${1}"

if [[ ! -f "${filename}" ]]; then
  echo "${filename} is not a file"
  usage
  exit 1
fi

export PAGER=less

###TODO prevent double decryption
if gpg --pinentry-mode loopback --cipher-algo AES256 --decrypt "${filename}" 2>&1 | grep -q "gpg: no valid OpenPGP data found." &> /dev/null; then
  echo "could not decrypt '${filename}' for viewing"
  exit 1
fi

gpg --pinentry-mode loopback --cipher-algo AES256 --decrypt "${filename}" 2> /dev/null | less
return_code=$?
if [[ ${return_code} -ne 0 ]]; then
  exit ${return_code}
fi
