#!/bin/bash

set -o nounset
set -o errexit
#set -o xtrace

if ! command -v gpg &> /dev/null; then
  echo "gpg is not installed"
  exit 1
fi

function usage() {
  echo "usage: $(basename $0) <filename>"
}

if [[ $# -ne 1 ]]; then
  usage
  exit 1
fi

filename="${1}"
filename_e="${filename}.gpg"

if [[ ! -f "${filename}" ]]; then
  echo "${filename} is not a file"
  usage
  exit 1
fi


gpg --pinentry-mode loopback --cipher-algo AES256 --output "${filename_e}" --symmetric "${filename}"
return_code=$?
if [[ ${return_code} -ne 0 ]]; then
  exit ${return_code}
fi

if [[ ! -f "${filename_e}" ]]; then
  echo "encrypted file '${filename_e}' not found, could not write to disk, something went wrong"
  exit 1
fi

rm -vi "${filename}"
